### ISSUE TITLE
Assignment 1 Is Complete

### ISSUE THREAD

**Issue by marygeschwindt** [VIS-2129-F2020/mgeschwindt-vis#1]
I have completed Assignment 1. My submitted assignment can be found here: https://vis-2129-f2020.github.io/mgeschwindt-vis/Assignment1.html

@c-voulgaris 
@bauranov

**Comment by bauranov** [comment]
Great work! The document is very clean and clear. I have very little to add:
- Figure 1: add {r, message=FALSE} to remove messages. In the legend, it makes sense to change income number format from scientific to regular. You can do that by adding label=comma into scale_size_continuous(name = "Income", label=comma).
- I really like Figure 3. Who are these 41-year-olds that are all taking a bus??

Keep up the good work!
