### ISSUE TITLE
Assignment 6: Projection Issue

### ISSUE THREAD

**Issue by marygeschwindt** [VIS-2129-F2020/mgeschwindt-vis#10]
I'm getting this error when trying to create my interactive map: **bounding box has potentially an invalid value range for longlat data**

It seems my code for the map is able to run, but the map created is a blank, gray box. After getting this error, I attempted to transform the projections for my 2 data layers to be the same CRS that the Leaflet package uses, but this did not resolve the error.

Here is a link to the HTML: https://vis-2129-f2020.github.io/mgeschwindt-vis/Assignment-6-Interactive-Map.html
To the RMD: https://github.com/VIS-2129-F2020/mgeschwindt-vis/blob/master/Assignment-6-Interactive-Map.Rmd

Please let me know if you have any input on why the map isn't working. Thank you!

**Comment by bauranov** [comment]
Hi Mary, some lat/long points in the *bikeracks* data are zeros, which is confusing R. Filter coordinates that are not zeros:

```{r}
bikeracks <- st_read("https://data.cityofnewyork.us/api/geospatial/yh4a-g3fj?method=export&format=GeoJSON") %>%
  filter(borough == "Manhattan") %>%
  st_transform(crs = leaflet_plane) %>% 
  filter(longitude !=0)
```

Additionally, I think you swapped lats and longs in the bounding box at the end of the code. Finally, I had to delete zoom limits, try playing with different values to see what works.
